/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as OfficialsRouteImport } from './routes/officials'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as VerifyRoleRouteImport } from './routes/verify.$role'
import { Route as ZoneZoneIdRouteImport } from './routes/zone.$zoneId'
import { Route as AuthenticatedReportCitizenRouteImport } from './routes/_authenticated.report.citizen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialsRoute = OfficialsRouteImport.update({
  id: '/officials',
  path: '/officials',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoleRoute = VerifyRoleRouteImport.update({
  id: '/verify/$role',
  path: '/verify/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const ZoneZoneIdRoute = ZoneZoneIdRouteImport.update({
  id: '/zone/$zoneId',
  path: '/zone/$zoneId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportCitizenRoute =
  AuthenticatedReportCitizenRouteImport.update({
    id: '/report/citizen',
    path: '/report/citizen',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/officials': typeof OfficialsRoute
  '/privacy': typeof PrivacyRoute
  '/verify/$role': typeof VerifyRoleRoute
  '/zone/$zoneId': typeof ZoneZoneIdRoute
  '/report/citizen': typeof AuthenticatedReportCitizenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/officials': typeof OfficialsRoute
  '/privacy': typeof PrivacyRoute
  '/verify/$role': typeof VerifyRoleRoute
  '/zone/$zoneId': typeof ZoneZoneIdRoute
  '/report/citizen': typeof AuthenticatedReportCitizenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/officials': typeof OfficialsRoute
  '/privacy': typeof PrivacyRoute
  '/verify/$role': typeof VerifyRoleRoute
  '/zone/$zoneId': typeof ZoneZoneIdRoute
  '/_authenticated/report/citizen': typeof AuthenticatedReportCitizenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/faq'
    | '/officials'
    | '/privacy'
    | '/verify/$role'
    | '/zone/$zoneId'
    | '/report/citizen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/faq'
    | '/officials'
    | '/privacy'
    | '/verify/$role'
    | '/zone/$zoneId'
    | '/report/citizen'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/faq'
    | '/officials'
    | '/privacy'
    | '/verify/$role'
    | '/zone/$zoneId'
    | '/_authenticated/report/citizen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRoute
  OfficialsRoute: typeof OfficialsRoute
  PrivacyRoute: typeof PrivacyRoute
  VerifyRoleRoute: typeof VerifyRoleRoute
  ZoneZoneIdRoute: typeof ZoneZoneIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officials': {
      id: '/officials'
      path: '/officials'
      fullPath: '/officials'
      preLoaderRoute: typeof OfficialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$role': {
      id: '/verify/$role'
      path: '/verify/$role'
      fullPath: '/verify/$role'
      preLoaderRoute: typeof VerifyRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zone/$zoneId': {
      id: '/zone/$zoneId'
      path: '/zone/$zoneId'
      fullPath: '/zone/$zoneId'
      preLoaderRoute: typeof ZoneZoneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/report/citizen': {
      id: '/_authenticated/report/citizen'
      path: '/report/citizen'
      fullPath: '/report/citizen'
      preLoaderRoute: typeof AuthenticatedReportCitizenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedReportCitizenRoute: typeof AuthenticatedReportCitizenRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedReportCitizenRoute: AuthenticatedReportCitizenRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRoute,
  OfficialsRoute: OfficialsRoute,
  PrivacyRoute: PrivacyRoute,
  VerifyRoleRoute: VerifyRoleRoute,
  ZoneZoneIdRoute: ZoneZoneIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
